
server.port=8090


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=

db.url=jdbc:postgresql://localhost:5432/postgres
db.username=postgres
db.password=



tg.app_id = 30421605
tg.hash = da59cb484ff2eaa3c53fff7474a0a85a
tg.phone = 79214887726
vk.token=vk1.a.Zk0SO1VKIkY1d-zBQYAidpN522HiFAXiDtCeNH2yZhBwtfPihpDhdruk_G0o5ry7iqBbm2Llrlm_pLRiNOeytTkmxxeBCG95l7EJREI2Ex3Nbux1QI2ixHc9FHyx5DKO3Uhd6nvvLMp4-Dz_eRnFDR7kOzHeCd51XcOr4c1SRLc-jAcnBMGZp67AVX7hW3hkGD6NqifVrbZfVtb-OBsYTA

app.auth.key=devkey


debug.enabled=true
